---
title: "Resume"
author: "Maykon da Silva"
date: "3/19/2022"
output: html_document
---

```{r setup, include = FALSE}
#Load all the good stuff
library(tidyverse)
library(forcats)
library(gt)
library(DataExplorer)
library(janitor)
library(paletteer)
library(webshot)

#Working directory for .RMD
knitr::opts_knit$set(echo = TRUE,
                     root.dir = rprojroot::find_rstudio_root_file())

#Controlling figure output in markdown
knitr::opts_chunk$set(
  fig.height =  10, 
  fig.width = 6,
#  fig.asp = .5,
  out.width = "90%",
#  out.height = 
 fig.align = "center",
  cache = FALSE,
  echo  = TRUE
)

#Set Theme for ggplot2 - centers title and legend at bottom by default
theme_set(theme(plot.title = element_text(hjust = 0.5), legend.position = "bottom"))

#Set Scientific notation output and decimal places for knitr
options(scipen = 999)
options(digits = 4)
```

# **Maykon Junior da Silva**

Falcon Heights, MN

E-mail: mjdasilv@umn.edu

## **Education**

**University of Minnesota:** Master of Science/MS. Soybean Production and Physiology
Lab – 2021/Current

**Federal University of Santa Maria (UFSM):** B. S. Agronomic Engineering (Agronomy and Crop Science), Santa Maria, Rio Grande do Sul, Brazil – 2013/2017.

## **Languages**

Portuguese: Native

English: Bilingual proficiency 

Spanish: Intermediary

## **Professional Experience:**

**CFANS – U of M College of Food, Agricultural and Natural Resources Sciences:** Graduate Research Assistant. (Jan, 2021 – Present).

Soybean research with emphasis in management strategies for Iron Deficiency Chlorosis. Designing experiments, coordinate field work to ensure implementation of protocols, taking detailed crop measurements throughout the growing season, conducting statistical analysis of biological data.

**CFANS – U of M College of Food, Agricultural and Natural Resources Sciences:** Student Trainee (May, 2019 – Oct, 2020).

Participation in several activities involving the conduction of research projects focused on soybean production and physiology across the state of Minnesota: packaging seeds, soil sampling, assisting with planting and harvesting, applying seed treatments, plot maintenance, drone operation.

**Fertilizantes Piratini Ltda:** Commercial Supervisor. (Jun, 2018 – May, 2019). 

Responsible for the commercialization of fertilizers for soybean, corn, and wheat producers in the South of Brazil. Responsible for the sale and delivery of fertilizers, prospecting of new clients, and maintenance of current customers (co-ops, sellers and farmers).

**Fertilizantes Piratini Ltda:** Commercial Trainee. (Mar, 2018 – Jun, 2018). 

Preparation period for Commercial Supervisor, focused on getting to know the region of operation and work methodology of the company.

**Tropical Plant Breeding and Genetics (TMG):** Trainee in the Soybean Breeding Program. (Aug, 2017 – Dec, 2017).

A mandatory internship held in Passo Fundo, Rio Grande do Sul, Brazil, and based on conducting field trials (management of offsprings, sowing of trials, pest and disease monitoring, evaluation of agronomic traits of interest, harvesting and processing).

**Tropical Plant Breeding and Genetics (TMG):** Trainee in the Soybean and Corn Breeding Programs. (Dec, 2016 – Mar, 2017).

Extracurricular internship in Rondonópolis-MT, which provided participation in all stages of the development of new cultivars of soybean and corn. Direct hybridization, conduction of field trials, agronomic characters evaluations and genetic seed production.

**Monsanto:** Trainee. 40 hours (Mar, 2017 – Mar, 2017)

Monsanto Prime Program: Participation in career fairs (Fair Expodireto 2017), providing the involvement in the different business areas of the company.

**Laboratory of Plant Breeding and Dry Bean Management (UFSM):** Scholarship and Voluntary Trainee. 20 hours/week (Sep, 2013 – Jul, 2017).

Development of new dry bean varieties for agronomic, nutritional, and cooking characteristics for the Southern region of Brazil.

## **Bibliographic Productions:**

**Articles published in scientific journals:**

1: POSSOBOM, M. T. D. F.; RIBEIRO, N. D.; CASAGRANDE, C. R.; **SILVA, M. J.** Inheritance pattern of zinc (Zn) concentration in Middle American and Andean common bean (*Phaseolus vulgaris* L.) seeds. AUSTRALIAN JOURNAL OF CROP SCIENCE (ONLINE), v. 12, p. 524-530, 2018.

2: RIBEIRO, NERINÉIA DALFOLLO; DE MARCO STECKLING, SKARLET; MAZIERO, SANDRA MARIA; **DA SILVA, MAYKON JUNIOR**; KLÄSENER, GREICE ROSANA; CASAGRANDE, CLEITON RENATO. Experimental precision of grain yield components and selection of superior common bean lines. EUPHYTICA, v. 213, p. 290, 2017.

3: ZEMOLIN, A. E. M.; RIBEIRO, N. D.; CASAGRANDE, C. R.; **SILVA, M. J.**; ARNS, F. D. Genetic parameters of iron and zinc concentrations in Andean common bean seeds. Acta Scientiarum. Agronomy (Online), 2016.
